<?php
namespace app\index\controller;

use think\Controller;
use think\Request;
use think\Exception;
use SoapClient;
use  SoapFault;
use SoapHeader;
use think\Image;

class Index extends Controller
{

    public function __construct(Request $request = null)
    {
        parent::__construct($request);
    }

    protected function _initialize(Request $request = null)
    {
        parent::_initialize(); // TODO: Change the autogenerated stub
    }


    public function index()
    {
        cache('a','a1');exit();


        $image = 'http://192.168.2.187:9091//media/5b20c171455a2.jpg';
//        $r = getimagesize($image);
$this->downPic($image,'');exit;
        $image = Image::open($image);
        var_dump($image);exit;

// 返回图片的宽度
        $width = $image->width();
// 返回图片的高度
        $height = $image->height();
// 返回图片的类型
        $type = $image->type();
// 返回图片的mime类型
        $mime = $image->mime();
// 返回图片的尺寸数组 0 图片宽度 1 图片高度
        $size = $image->size();
        try{
            $options = array (
                'uri' => '',
                'location' => '111', //注意: 这个location指定的是server端代码在服务器中的具体位置, 我的是在本地根目录下的soap目录中,
                'trace' => true,
                'exceptions'=>true
            );
            $client = new SoapClient ( null, $options );
//            $client->SoapClient('');
            //SoapHeader  身份认证。让具体指定用户口令的用户来访问我们的web服务接口。
//            SoapClient->SoapClient($url, array("trace" => 1, "exception" => 1));
//            $client     = new \SoapClient($url, array("trace" => 1, "exception" => 1));
        }catch (\SoapFault $e){
            echo 22;
        }catch (Exception $e){
            echo 1;
        }
//        return '<style type="text/css">*{ padding: 0; margin: 0; } .think_default_text{ padding: 4px 48px;} a{color:#2E5CD5;cursor: pointer;text-decoration: none} a:hover{text-decoration:underline; } body{ background: #fff; font-family: "Century Gothic","Microsoft yahei"; color: #333;font-size:18px} h1{ font-size: 100px; font-weight: normal; margin-bottom: 12px; } p{ line-height: 1.6em; font-size: 42px }</style><div style="padding: 24px 48px;"> <h1>:)</h1><p> ThinkPHP V5<br/><span style="font-size:30px">十年磨一剑 - 为API开发设计的高性能框架</span></p><span style="font-size:22px;">[ V5.0 版本由 <a href="http://www.qiniu.com" target="qiniu">七牛云</a> 独家赞助发布 ]</span></div><script type="text/javascript" src="https://tajs.qq.com/stats?sId=9347272" charset="UTF-8"></script><script type="text/javascript" src="https://e.topthink.com/Public/static/client.js"></script><think id="ad_bd568ce7058a1091"></think>';
        return $this->fetch();
    }
    function downPic($file_url,$path)
    {
        $save_name = date('YmdHis')."111".'.jpeg';
        $save_to = 'http://192.168.2.187:9091//media/'.$save_name;
        $content = file_get_contents($file_url);
        $re = file_put_contents($save_to, $content);
    }
    public function read()
    {
        return json_encode(['a'=>1]);
    }
    public function index3()
    {
        echo 33;
    }
    public function index2()
    {
        echo 22;
    }
}
